/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TeacherRouteImport } from './routes/_teacher'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeTestIdRouteImport } from './routes/practice.$testId'
import { Route as TeacherTeacherRouteImport } from './routes/_teacher.teacher'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as PracticeTestIdResultsAttemptIdRouteImport } from './routes/practice.$testId.results.$attemptId'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/_teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTestIdRoute = PracticeTestIdRouteImport.update({
  id: '/practice/$testId',
  path: '/practice/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherRoute = TeacherTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const PracticeTestIdResultsAttemptIdRoute =
  PracticeTestIdResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => PracticeTestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AdminAdminRoute
  '/teacher': typeof TeacherTeacherRoute
  '/practice/$testId': typeof PracticeTestIdRouteWithChildren
  '/practice/': typeof PracticeIndexRoute
  '/practice/$testId/results/$attemptId': typeof PracticeTestIdResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AdminAdminRoute
  '/teacher': typeof TeacherTeacherRoute
  '/practice/$testId': typeof PracticeTestIdRouteWithChildren
  '/practice': typeof PracticeIndexRoute
  '/practice/$testId/results/$attemptId': typeof PracticeTestIdResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_teacher': typeof TeacherRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_teacher/teacher': typeof TeacherTeacherRoute
  '/practice/$testId': typeof PracticeTestIdRouteWithChildren
  '/practice/': typeof PracticeIndexRoute
  '/practice/$testId/results/$attemptId': typeof PracticeTestIdResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/dashboard'
    | '/progress'
    | '/admin'
    | '/teacher'
    | '/practice/$testId'
    | '/practice/'
    | '/practice/$testId/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/dashboard'
    | '/progress'
    | '/admin'
    | '/teacher'
    | '/practice/$testId'
    | '/practice'
    | '/practice/$testId/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_teacher'
    | '/auth'
    | '/bookmarks'
    | '/dashboard'
    | '/progress'
    | '/_admin/admin'
    | '/_teacher/teacher'
    | '/practice/$testId'
    | '/practice/'
    | '/practice/$testId/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  ProgressRoute: typeof ProgressRoute
  PracticeTestIdRoute: typeof PracticeTestIdRouteWithChildren
  PracticeIndexRoute: typeof PracticeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_teacher': {
      id: '/_teacher'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$testId': {
      id: '/practice/$testId'
      path: '/practice/$testId'
      fullPath: '/practice/$testId'
      preLoaderRoute: typeof PracticeTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_teacher/teacher': {
      id: '/_teacher/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherTeacherRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/practice/$testId/results/$attemptId': {
      id: '/practice/$testId/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/practice/$testId/results/$attemptId'
      preLoaderRoute: typeof PracticeTestIdResultsAttemptIdRouteImport
      parentRoute: typeof PracticeTestIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeacherRouteChildren {
  TeacherTeacherRoute: typeof TeacherTeacherRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherTeacherRoute: TeacherTeacherRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

interface PracticeTestIdRouteChildren {
  PracticeTestIdResultsAttemptIdRoute: typeof PracticeTestIdResultsAttemptIdRoute
}

const PracticeTestIdRouteChildren: PracticeTestIdRouteChildren = {
  PracticeTestIdResultsAttemptIdRoute: PracticeTestIdResultsAttemptIdRoute,
}

const PracticeTestIdRouteWithChildren = PracticeTestIdRoute._addFileChildren(
  PracticeTestIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  ProgressRoute: ProgressRoute,
  PracticeTestIdRoute: PracticeTestIdRouteWithChildren,
  PracticeIndexRoute: PracticeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
